package com.example.chanwon.appsent.emotion.util;

import java.util.ArrayList;
import java.util.List;

/**
 * Created by CHANWON on 6/08/2015.
 */
public class TestData {
    public ArrayList<String> testdata;

    public ArrayList<String> getchanwonAffectWords() {
        testdata = new ArrayList<String>();
        testdata.add("5	Emerges as something rare , an issue movie that 's so honest and keenly observed that it does n't feel like one .");
        testdata.add("6	The film provides some great insight into the neurotic mindset of all comics -- even those who have reached the absolute top of the game .");
        testdata.add("7	Offers that rare combination of entertainment and education .");
        testdata.add("8	Perhaps no picture ever made has more literally showed that the road to hell is paved with good intentions .");
        testdata.add("9	Steers turns in a snappy screenplay that curls at the edges ; it 's so clever you want to hate it .");
        testdata.add("10	But he somehow pulls it off .");
        testdata.add("11	Take Care of My Cat offers a refreshingly different slice of Asian cinema .");
        testdata.add("12	This is a film well worth seeing , talking and singing heads and all .");
        testdata.add("13	What really surprises about Wisegirls is its low-key quality and genuine tenderness .");
        testdata.add("14	-LRB- Wendigo is -RRB- why we go to the cinema : to be fed through the eye , the heart , the mind .");
        testdata.add("15	One of the greatest family-oriented , fantasy-adventure movies ever .");
        testdata.add("16	Ultimately , it ponders the reasons we need stories so much .");
        testdata.add("17	An utterly compelling ` who wrote it ' in which the reputation of the most famous author who ever lived comes into question .");
        testdata.add("18	Illuminating if overly talky documentary .");
        testdata.add("19	A masterpiece four years in the making .");
        testdata.add("20	The movie 's ripe , enrapturing beauty will tempt those willing to probe its inscrutable mysteries .");
        testdata.add("21	Offers a breath of the fresh air of true sophistication .");
        testdata.add("22	A thoughtful , provocative , insistently humanizing film .");
        testdata.add("23	With a cast that includes some of the top actors working in independent film , Lovely & Amazing involves us because it is so incisive , so bleakly amusing about how we go about our lives .");
        testdata.add("24	A disturbing and frighteningly evocative assembly of imagery and hypnotic music composed by Philip Glass .");
        testdata.add("25	Not for everyone , but for those with whom it will connect , it 's a nice departure from standard moviegoing fare .");
        testdata.add("26	Scores a few points for doing what it does with a dedicated and good-hearted professionalism .");
        testdata.add("27	Occasionally melodramatic , it 's also extremely effective .");
        testdata.add("28	An idealistic love story that brings out the latent 15-year-old romantic in everyone .");
        testdata.add("29	At about 95 minutes , Treasure Planet maintains a brisk pace as it races through the familiar story .");
        testdata.add("30	However , it lacks grandeur and that epic quality often associated with Stevenson 's tale as well as with earlier Disney efforts .");
        testdata.add("31	It helps that Lil Bow Wow ... tones down his pint-sized gangsta act to play someone who resembles a real kid .");
        testdata.add("32	Guaranteed to move anyone who ever shook , rattled , or rolled .");
        testdata.add("33	A masterful film from a master filmmaker , unique in its deceptive grimness , compelling in its fatalist worldview .");
        testdata.add("34	Light , cute and forgettable .");
        testdata.add("35	If there 's a way to effectively teach kids about the dangers of drugs , I think it 's in projects like the -LRB- unfortunately R-rated -RRB- Paid .");
        testdata.add("36	While it would be easy to give Crush the new title of Two Weddings and a Funeral , it 's a far more thoughtful film than any slice of Hugh Grant whimsy .");
        testdata.add("37	Though everything might be literate and smart , it never took off and always seemed static .");
        testdata.add("40	Though it is by no means his best work , Laissez-Passer is a distinguished and distinctive effort by a bona-fide master , a fascinating film replete with rewards to be had by all willing to make the effort to reap them .");
        testdata.add("41	Like most Bond outings in recent years , some of the stunts are so outlandish that they border on being cartoonlike .");
        testdata.add("42	A heavy reliance on CGI technology is beginning to creep into the series .");
        testdata.add("43	Newton draws our attention like a magnet , and acts circles around her better known co-star , Mark Wahlberg .");
        testdata.add("44	The story loses its bite in a last-minute happy ending that 's even less plausible than the rest of the picture .");
        testdata.add("45	Much of the way , though , this is a refreshingly novel ride .");
        testdata.add("46	Fuller would surely have called this gutsy and at times exhilarating movie a great yarn .");
        testdata.add("47	The film makes a strong case for the importance of the musicians in creating the Motown sound .");
        testdata.add("48	Karmen moves like rhythm itself , her lips chanting to the beat , her long , braided hair doing little to wipe away the jeweled beads of sweat .");
        testdata.add("49	Gosling provides an amazing performance that dwarfs everything else in the film .");
        testdata.add("50	A real movie , about real people , that gives us a rare glimpse into a culture most of us do n't know .");
        testdata.add("51	Tender yet lacerating and darkly funny fable .");
        testdata.add("52	May be spoofing an easy target -- those old ' 50 's giant creature features -- but ... it acknowledges and celebrates their cheesiness as the reason why people get a kick out of watching them today .");
        testdata.add("53	An engaging overview of Johnson 's eccentric career .");
        testdata.add("54	In its ragged , cheap and unassuming way , the movie works .");
        testdata.add("55	Some actors have so much charisma that you 'd be happy to listen to them reading the phone book .");
        testdata.add("56	Hugh Grant and Sandra Bullock are two such likeable actors .");
        testdata.add("57	Sandra Nettelbeck beautifully orchestrates the transformation of the chilly , neurotic , and self-absorbed Martha as her heart begins to open .");
        testdata.add("58	Behind the snow games and lovable Siberian huskies -LRB- plus one sheep dog -RRB- , the picture hosts a parka-wrapped dose of heart .");
        testdata.add("59	Everytime you think Undercover Brother has run out of steam , it finds a new way to surprise and amuse .");
        testdata.add("60	Manages to be original , even though it rips off many of its ideas .");
        testdata.add("62	You 'd think by now America would have had enough of plucky British eccentrics with hearts of gold .");
        testdata.add("63	Yet the act is still charming here .");
        testdata.add("64	Whether or not you 're enlightened by any of Derrida 's lectures on `` the other '' and `` the self , '' Derrida is an undeniably fascinating and playful fellow .");
        testdata.add("65	A pleasant enough movie , held together by skilled ensemble actors .");
        testdata.add("66	This is the best American movie about troubled teens since 1998 's Whatever .");
        testdata.add("67	Disney has always been hit-or-miss when bringing beloved kids ' books to the screen ... Tuck Everlasting is a little of both .");
        testdata.add("68	Just the labour involved in creating the layered richness of the imagery in this chiaroscuro of madness and light is astonishing .");
        testdata.add("69	The animated subplot keenly depicts the inner struggles of our adolescent heroes - insecure , uncontrolled , and intense .");
        testdata.add("72	Part of the charm of Satin Rouge is that it avoids the obvious with humour and lightness .");
        testdata.add("73	Son of the Bride may be a good half-hour too long but comes replete with a flattering sense of mystery and quietness .");
        testdata.add("74	A simmering psychological drama in which the bursts of sudden violence are all the more startling for the slow buildup that has preceded them .");
        testdata.add("75	A taut , intelligent psychological drama .");
        testdata.add("76	A truly moving experience , and a perfect example of how art -- when done right -- can help heal , clarify , and comfort .");
        testdata.add("77	This delicately observed story , deeply felt and masterfully stylized , is a triumph for its maverick director .");
        testdata.add("78	At heart the movie is a deftly wrought suspense yarn whose richer shadings work as coloring rather than substance .");
        testdata.add("79	The appearance of Treebeard and Gollum 's expanded role will either have you loving what you 're seeing , or rolling your eyes .");
        testdata.add("80	I loved it !");
        testdata.add("81	Gollum 's ` performance ' is incredible !");
        testdata.add("84	Haneke challenges us to confront the reality of sexual aberration .");
        testdata.add("85	Absorbing and disturbing -- perhaps more disturbing than originally intended -- but a little clarity would have gone a long way .");
        testdata.add("86	It 's the best film of the year so far , the benchmark against which all other Best Picture contenders should be measured .");
        testdata.add("87	Painful to watch , but viewers willing to take a chance will be rewarded with two of the year 's most accomplished and riveting film performances .");
        testdata.add("88	This is a startling film that gives you a fascinating , albeit depressing view of Iranian rural life close to the Iraqi border .");
        testdata.add("89	A few artsy flourishes aside , Narc is as gritty as a movie gets these days .");
        testdata.add("90	While The Isle is both preposterous and thoroughly misogynistic , its vistas are incredibly beautiful to look at .");
        testdata.add("91	Together , Tok and O orchestrate a buoyant , darkly funny dance of death .");
        testdata.add("92	In the process , they demonstrate that there 's still a lot of life in Hong Kong cinema .");
        testdata.add("93	Director Kapur is a filmmaker with a real flair for epic landscapes and adventure , and this is a better film than his earlier English-language movie , the overpraised Elizabeth .");
        testdata.add("94	The movie is a blast of educational energy , as bouncy animation and catchy songs escort you through the entire 85 minutes .");
        testdata.add("95	A sports movie with action that 's exciting on the field and a story you care about off it .");
        testdata.add("96	Doug Liman , the director of Bourne , directs the traffic well , gets a nice wintry look from his locations , absorbs us with the movie 's spycraft and uses Damon 's ability to be focused and sincere .");
        testdata.add("97	The tenderness of the piece is still intact .");
        testdata.add("100	While McFarlane 's animation lifts the film firmly above the level of other coming-of-age films ... it 's also so jarring that it 's hard to get back into the boys ' story .");
        testdata.add("101	If nothing else , this movie introduces a promising , unusual kind of psychological horror .");
        testdata.add("102	In a normal screen process , these bromides would be barely enough to sustain an interstitial program on the Discovery Channel .");
        testdata.add("103	But in Imax 3-D , the clichÃ©s disappear into the vertiginous perspectives opened up by the photography .");
        testdata.add("104	Writer-director Burger imaginatively fans the embers of a dormant national grief and curiosity that has calcified into chronic cynicism and fear .");
        testdata.add("107	Chicago is sophisticated , brash , sardonic , completely joyful in its execution .");
        testdata.add("108	Steve Irwin 's method is Ernest Hemmingway at accelerated speed and volume .");
        testdata.add("109	A refreshing Korean film about five female high school friends who face an uphill battle when they try to take their relationships into deeper waters .");
        testdata.add("110	On the surface , it 's a lovers-on-the-run crime flick , but it has a lot in common with Piesiewicz 's and Kieslowski 's earlier work , films like The Double Life of Veronique .");
        testdata.add("111	The values that have held the Enterprise crew together through previous adventures and perils do so again-courage , self-sacrifice and patience under pressure .");
        testdata.add("112	If it 's possible for a sequel to outshine the original , then SL2 does just that .");
        testdata.add("113	A romantic comedy that operates by the rules of its own self-contained universe .");
        testdata.add("114	4 friends , 2 couples , 2000 miles , and all the Pabst Blue Ribbon beer they can drink - it 's the ultimate redneck road-trip .");
        testdata.add("117	A feel-good picture in the best sense of the term .");
        testdata.add("118	Edited and shot with a syncopated style mimicking the work of his subjects , Pray turns the idea of the documentary on its head , making it rousing , invigorating fun lacking any MTV puffery .");
        testdata.add("119	A mostly intelligent , engrossing and psychologically resonant suspenser .");
        testdata.add("120	It 's this memory-as-identity obviation that gives Secret Life its intermittent unease , reaffirming that long-held illusions are indeed reality , and that erasing them recasts the self .");
        testdata.add("121	Hip-hop has a history , and it 's a metaphor for this love story .");
        testdata.add("122	In scope , ambition and accomplishment , Children of the Century ... takes Kurys ' career to a whole new level .");
        testdata.add("123	This may not have the dramatic gut-wrenching impact of other Holocaust films , but it 's a compelling story , mainly because of the way it 's told by the people who were there .");
        testdata.add("124	Between the drama of Cube ?");
        testdata.add("125	s personal revelations regarding what the shop means in the big picture , iconic characters gambol fluidly through the story , with charming results .");
        testdata.add("126	A gentle , compassionate drama about grief and healing .");
        testdata.add("127	Somewhere short of Tremors on the modern B-scene : neither as funny nor as clever , though an agreeably unpretentious way to spend ninety minutes .");
        testdata.add("128	Digital-video documentary about stand-up comedians is a great glimpse into a very different world .");
        testdata.add("129	Unlike most teen flicks , Swimming takes its time to tell its story , casts mostly little-known performers in key roles , and introduces some intriguing ambiguity .");
        testdata.add("130	An enthralling , playful film that constantly frustrates our desire to know the ` truth ' about this man , while deconstructing the very format of the biography in a manner that Derrida would doubtless give his blessing to .");
        testdata.add("131	`` Extreme Ops '' exceeds expectations .");
        testdata.add("132	Good fun , good action , good acting , good dialogue , good pace , good cinematography .");
        testdata.add("133	You Should Pay Nine Bucks for This : Because you can hear about suffering Afghan refugees on the news and still be unaffected .");
        testdata.add("134	Dramas like this make it human .");
        testdata.add("135	A thunderous ride at first , quiet cadences of pure finesse are few and far between ; their shortage dilutes the potency of otherwise respectable action .");
        testdata.add("136	Still , this flick is fun , and host to some truly excellent sequences .");
        testdata.add("137	It 's obviously struck a responsive chord with many South Koreans , and should work its magic in other parts of the world .");
        testdata.add("138	Run , do n't walk , to see this barbed and bracing comedy on the big screen .");
        testdata.add("139	A classy item by a legend who may have nothing left to prove but still has the chops and drive to show how its done .");
        testdata.add("140	It is nature against progress .");
        testdata.add("141	In Fessenden 's horror trilogy , this theme has proved important to him and is especially so in the finale .");
        testdata.add("142	It 's not exactly a gourmet meal but the fare is fair , even coming from the drive-thru .");
        testdata.add("143	This is what IMAX was made for : Strap on a pair of 3-D goggles , shut out the real world , and take a vicarious voyage to the last frontier -- space .");
        testdata.add("144	Merely as a technical , logistical feat , Russian Ark marks a cinematic milestone .");
        testdata.add("145	-LRB- Schweiger is -RRB- talented and terribly charismatic , qualities essential to both movie stars and social anarchists .");
        testdata.add("146	It 's a great deal of sizzle and very little steak .");
        testdata.add("147	But what spectacular sizzle it is !");
        testdata.add("148	... In this incarnation its fizz is infectious .");
        testdata.add("149	An original gem about an obsession with time .");
        testdata.add("150	It will delight newcomers to the story and those who know it from bygone days .");
        testdata.add("151	Gloriously goofy -LRB- and gory -RRB- midnight movie stuff .");
        testdata.add("152	The film overcomes the regular minefield of coming-of-age cliches with potent doses of honesty and sensitivity .");
        testdata.add("153	If your senses have n't been dulled by slasher films and gorefests , if you 're a connoisseur of psychological horror , this is your ticket .");
        testdata.add("154	It 's a minor comedy that tries to balance sweetness with coarseness , while it paints a sad picture of the singles scene .");
        testdata.add("155	It is intensely personal and yet -- unlike Quills -- deftly shows us the temper of the times .");
        testdata.add("156	As lo-fi as the special effects are , the folks who cobbled Nemesis together indulge the force of humanity over hardware in a way that George Lucas has long forgotten .");
        testdata.add("157	Like Mike does n't win any points for originality .");
        testdata.add("158	It does succeed by following a feel-good formula with a winning style , and by offering its target audience of urban kids some welcome role models and optimism .");
        testdata.add("159	It 's a hoot and a half , and a great way for the American people to see what a candidate is like when he 's not giving the same 15-cent stump speech .");
        testdata.add("160	Far from perfect , but its heart is in the right place ... innocent and well-meaning .");
        testdata.add("161	A sad , superior human comedy played out on the back roads of life .");
        testdata.add("162	Waydowntown is by no means a perfect film , but its boasts a huge charm factor and smacks of originality .");
        testdata.add("163	Tim Allen is great in his role but never hogs the scenes from his fellow cast , as there are plenty of laughs and good lines for everyone in this comedy .");
        testdata.add("164	More a load of enjoyable , Conan-esque claptrap than the punishing , special-effects soul assaults the Mummy pictures represent .");
        testdata.add("165	Enormously likable , partly because it is aware of its own grasp of the absurd .");
        testdata.add("166	Here 's a British flick gleefully unconcerned with plausibility , yet just as determined to entertain you .");
        testdata.add("167	It 's an old story , but a lively script , sharp acting and partially animated interludes make Just a Kiss seem minty fresh .");
        testdata.add("168	Must be seen to be believed .");
        testdata.add("169	Ray Liotta and Jason Patric do some of their best work in their underwritten roles , but do n't be fooled : Nobody deserves any prizes here .");
        testdata.add("170	Everything that has to do with Yvan and Charlotte , and everything that has to do with Yvan 's rambunctious , Jewish sister and her non-Jew husband , feels funny and true .");
        testdata.add("171	The year 's happiest surprise , a movie that deals with a real subject in an always surprising way .");
        testdata.add("172	Fans of Behan 's work and of Irish movies in general will be rewarded by Borstal Boy .");
        testdata.add("173	Its mysteries are transparently obvious , and it 's too slowly paced to be a thriller .");
        testdata.add("174	-LRB- But it 's -RRB- worth recommending because of two marvelous performances by Michael Caine and Brendan Fraser .");
        testdata.add("175	The film is faithful to what one presumes are the book 's twin premises -- that we become who we are on the backs of our parents , but we have no idea who they were at our age ; and that time is a fleeting and precious commodity no matter how old you are .");
        testdata.add("176	Stephen Earnhart 's homespun documentary Mule Skinner Blues has nothing but love for its posse of trailer park denizens .");
        testdata.add("177	A solidly seaworthy chiller .");
        testdata.add("178	If you can get past the fantastical aspects and harsh realities of `` The Isle '' you 'll get a sock-you-in-the-eye flick that is a visual tour-de-force and a story that is unlike any you will likely see anywhere else .");
        testdata.add("179	There are as many misses as hits , but ultimately , it finds humor in the foibles of human behavior , and it 's a welcome return to the roots of a genre that should depend on surprises .");
        testdata.add("180	A well-made thriller with a certain level of intelligence and non-reactionary morality .");
        testdata.add("181	There 's enough science to make it count as educational , and enough beauty to make it unforgettable .");
        testdata.add("182	Remains a solid , if somewhat heavy-handed , account of the near-disaster ... done up by Howard with a steady , if not very imaginative , hand .");
        testdata.add("183	Makmalbaf follows a resolutely realistic path in this uncompromising insight into the harsh existence of the Kurdish refugees of Iran 's borderlands .");
        testdata.add("184	For a good chunk of its running time , Trapped is an effective and claustrophobic thriller .");
        testdata.add("185	Most of Crush is a clever and captivating romantic comedy with a welcome pinch of tartness .");
        testdata.add("188	Rare is the ` urban comedy ' that even attempts the insight and honesty of this disarming indie .");
        testdata.add("189	Ranks among Willams ' best screen work .");
        testdata.add("190	Engagingly captures the maddening and magnetic ebb and flow of friendship .");
        testdata.add("191	An experience so engrossing it is like being buried in a new environment .");
        testdata.add("192	It 's traditional moviemaking all the way , but it 's done with a lot of careful period attention as well as some very welcome wit .");
        testdata.add("193	Maybe it 's just because this past year has seen the release of some of the worst film comedies in decades ... But honestly , Analyze That really is n't all that bad .");
        testdata.add("194	A droll , well-acted , character-driven comedy with unexpected deposits of feeling .");
        testdata.add("195	This is simply the most fun you 'll ever have with a documentary !");
        testdata.add("196	A very funny movie .");
        testdata.add("197	Watching Haneke 's film is , aptly enough , a challenge and a punishment .");
        testdata.add("198	But watching Huppert , a great actress tearing into a landmark role , is riveting .");
        testdata.add("199	A cop story that understands the medium amazingly well .");
        return testdata;
        //System.out.println();
    }
}
